export const CREATE_TODO = "CREATE_TODO"

export const DELETE_TODO = "DELETE_TODO"

export const COMPLETED_TODO = "COMPLETED_TODO"

export const DELETE_COMPLETED_TODOS = "DELETE_COMPLETED_TODOS"

export const CHECK_ALL = "CHECK_ALL"

export const UNCHECK_ALL = "UNCHECK_ALL"

export const COMPLETED_TODOS = "COMPLETED_TODOS"

export const ACTIVE_TODOS = "ACTIVE_TODOS"

export const ALL_TODOS = "ALL_TODOS"